In [3]:
## Importing libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [4]:
## Reading the file

df = pd.read_csv('/content/Customer-Churn (1).csv')

In [5]:
df.head(5)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [6]:
df.Churn.value_counts()/len(df)*100

Churn
No     73.463013
Yes    26.536987
Name: count, dtype: float64

## **Churn Rate**: 26.53%

- Which means, 26.53% of the customers churn out of this telecom company

In [7]:
## Divide data into X and y - X (Independent features), y(Dependent variable)

# Define y (target variable)
y = df['Churn']

# Define X (features) by dropping 'customerID' and 'Churn'
X = df.drop(columns=['customerID', 'Churn'])

# Optional: Verify the shapes
print("Shape of X:", X.shape)
print("Shape of y:", y.shape)

Shape of X: (7043, 19)
Shape of y: (7043,)

## Train Test Split

In [8]:
X = pd.get_dummies(X, drop_first=True)
y = df['Churn'].map({'No': 0, 'Yes': 1})

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

## Model Building

In [10]:
model_dt = DecisionTreeClassifier()
model_dt.fit(X_train, y_train)

DecisionTreeClassifier()

In [11]:
y_pred_dt = model_dt.predict(X_test)

In [12]:
print(classification_report(y_test, y_pred_dt))

              precision    recall  f1-score   support

           0       0.84      0.86      0.85      1045
           1       0.56      0.52      0.54       364

    accuracy                           0.77      1409
   macro avg       0.70      0.69      0.69      1409
weighted avg       0.77      0.77      0.77      1409

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

## Initial Insights

- Base model has a accuracy of 76% which is not reliable because of the imbalanced dataset
- TotalCharges needs to be a float/int type (Data Cleaning)
- Need to perform Feature Scaling

## Data Cleaning

In [14]:
telco_data = df.copy()

In [15]:
telco_data.TotalCharges = pd.to_numeric(telco_data.TotalCharges, errors='coerce')

In [16]:
telco_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7043 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.1+ MB

In [17]:
telco_data.loc[telco_data['TotalCharges'].isnull() == True]

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
488,4472-LVYGI,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,Yes,Bank transfer (automatic),52.55,NaN,No
753,3115-CZMZD,Male,0,No,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.25,NaN,No
936,5709-LVOEQ,Female,0,Yes,Yes,0,Yes,No,DSL,Yes,...,Yes,No,Yes,Yes,Two year,No,Mailed check,80.85,NaN,No
1082,4367-NUYAO,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.75,NaN,No
1340,1371-DWPAZ,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,No,Credit card (automatic),56.05,NaN,No
3331,7644-OMVMY,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.85,NaN,No
3826,3213-VVOLG,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.35,NaN,No
4380,2520-SGTTA,Female,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.00,NaN,No
5218,2923-ARZLG,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,One year,Yes,Mailed check,19.70,NaN,No
6670,4075-WKNIU,Female,0,Yes,Yes,0,Yes,Yes,DSL,No,...,Yes,Yes,Yes,No,Two year,No,Mailed check,73.35,NaN,No
6754,2775-SEFEE,Male,0,No,Yes,0,Yes,Yes,DSL,Yes,...,No,Yes,No,No,Two year,Yes,Bank transfer (automatic),61.90,NaN,No

In [18]:
telco_data.dropna(how='any', inplace=True)

In [19]:
telco_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7032 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7032 non-null   object
 1   gender            7032 non-null   object
 2   SeniorCitizen     7032 non-null   int64
 3   Partner           7032 non-null   object
 4   Dependents        7032 non-null   object
 5   tenure            7032 non-null   int64
 6   PhoneService      7032 non-null   object
 7   MultipleLines     7032 non-null   object
 8   InternetService   7032 non-null   object
 9   OnlineSecurity    7032 non-null   object
 10  OnlineBackup      7032 non-null   object
 11  DeviceProtection  7032 non-null   object
 12  TechSupport       7032 non-null   object
 13  StreamingTV       7032 non-null   object
 14  StreamingMovies   7032 non-null   object
 15  Contract          7032 non-null   object
 16  PaperlessBilling  7032 non-null   object
 17  PaymentMethod     7032 non-null   object
 18  MonthlyCharges    7032 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7032 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.2+ MB

In [20]:
telco_data.head(5)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [21]:
telco_data.tenure.max()

72

In [22]:
import pandas as pd

# Define the bin edges (0 to 72, stepping by 12 months)
bins = [0, 12, 24, 36, 48, 60, 72]

# Define the labels for each bin
labels = ['1-12', '13-24', '25-36', '37-48', '49-60', '61-72']

# Create the new binned column
telco_data['tenure_bin'] = pd.cut(telco_data['tenure'], bins=bins, labels=labels, include_lowest=True)

# Optional: Check the result
print(telco_data[['tenure', 'tenure_bin']].head(10))
print(telco_data['tenure_bin'].value_counts().sort_index())

   tenure tenure_bin
0       1       1-12
1      34      25-36
2       2       1-12
3      45      37-48
4       2       1-12
5       8       1-12
6      22      13-24
7      10       1-12
8      28      25-36
9      62      61-72
tenure_bin
1-12     2175
13-24    1024
25-36     832
37-48     762
49-60     832
61-72    1407
Name: count, dtype: int64

In [23]:
telco_data.head(5)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,tenure_bin
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No,1-12
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,No,No,No,One year,No,Mailed check,56.95,1889.50,No,25-36
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1-12
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No,37-48
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,1-12

In [24]:
## Divide data into X and y - X (Independent features), y(Dependent variable)

# Define y (target variable)
y = telco_data['Churn']

# Define X (features) by dropping 'customerID' and 'Churn'
X = telco_data.drop(columns=['customerID', 'Churn', 'tenure'])

# Optional: Verify the shapes
print("Shape of X:", X.shape)
print("Shape of y:", y.shape)

Shape of X: (7032, 19)
Shape of y: (7032,)

In [25]:
X

,gender,SeniorCitizen,Partner,Dependents,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,tenure_bin
0,Female,0,Yes,No,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,1-12
1,Male,0,No,No,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,25-36
2,Male,0,No,No,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,1-12
3,Male,0,No,No,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,37-48
4,Female,0,No,No,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,1-12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,Male,0,Yes,Yes,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.50,13-24
7039,Female,0,Yes,Yes,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.90,61-72
7040,Female,0,Yes,Yes,No,No phone service,DSL,Yes,No,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,1-12
7041,Male,1,Yes,No,Yes,Yes,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.60,1-12
7042,Male,0,No,No,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.50,61-72

In [26]:
X = pd.get_dummies(X, drop_first=True)
y = telco_data['Churn'].map({'No': 0, 'Yes': 1})

In [27]:
X

,SeniorCitizen,MonthlyCharges,TotalCharges,gender_Male,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_No phone service,MultipleLines_Yes,InternetService_Fiber optic,...,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,tenure_bin_13-24,tenure_bin_25-36,tenure_bin_37-48,tenure_bin_49-60,tenure_bin_61-72
0,0,29.85,29.85,False,True,False,False,True,False,False,...,False,True,False,True,False,False,False,False,False,False
1,0,56.95,1889.50,True,False,False,True,False,False,False,...,False,False,False,False,True,False,True,False,False,False
2,0,53.85,108.15,True,False,False,True,False,False,False,...,False,True,False,False,True,False,False,False,False,False
3,0,42.30,1840.75,True,False,False,False,True,False,False,...,False,False,False,False,False,False,False,True,False,False
4,0,70.70,151.65,False,False,False,True,False,False,True,...,False,True,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,0,84.80,1990.50,True,True,True,True,False,True,False,...,False,True,False,False,True,True,False,False,False,False
7039,0,103.20,7362.90,False,True,True,True,False,True,True,...,False,True,True,False,False,False,False,False,False,True
7040,0,29.60,346.45,False,True,True,False,True,False,False,...,False,True,False,True,False,False,False,False,False,False
7041,1,74.40,306.60,True,True,False,True,False,True,True,...,False,True,False,False,True,False,False,False,False,False
7042,0,105.65,6844.50,True,False,False,True,False,False,True,...,True,True,False,False,False,False,False,False,False,True

In [28]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

## Feature Scaling

In [29]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [30]:
model_dt2 = DecisionTreeClassifier()
model_dt2.fit(X_train, y_train)

y_pred_dt2 = model_dt2.predict(X_test)

In [31]:
print(classification_report(y_test, y_pred_dt2))

              precision    recall  f1-score   support

           0       0.81      0.81      0.81      1049
           1       0.45      0.46      0.46       358

    accuracy                           0.72      1407
   macro avg       0.63      0.64      0.63      1407
weighted avg       0.72      0.72      0.72      1407

## Feature Scaling - MinMaxScaler

In [32]:
mms = MinMaxScaler()
X_train_mms = mms.fit_transform(X_train)
X_test_mms = mms.transform(X_test)

In [33]:
model_dt3 = DecisionTreeClassifier()
model_dt3.fit(X_train_mms, y_train)

y_pred_dt3 = model_dt3.predict(X_test_mms)

In [34]:
print(classification_report(y_test, y_pred_dt3))

              precision    recall  f1-score   support

           0       0.81      0.81      0.81      1049
           1       0.43      0.42      0.43       358

    accuracy                           0.71      1407
   macro avg       0.62      0.62      0.62      1407
weighted avg       0.71      0.71      0.71      1407

## SMOTEENN () [UpSampling + ENN)

In [35]:
from imblearn.combine import SMOTEENN

In [36]:
sm = SMOTEENN()
X_train_resampled, y_train_resampled = sm.fit_resample(X_train, y_train)

In [37]:
model_dt_smoteenn = DecisionTreeClassifier()
model_dt_smoteenn.fit(X_train_resampled, y_train_resampled)

y_pred_dt_smoteenn = model_dt_smoteenn.predict(X_test)

In [38]:
print(classification_report(y_test, y_pred_dt_smoteenn))

              precision    recall  f1-score   support

           0       0.89      0.71      0.79      1049
           1       0.47      0.75      0.58       358

    accuracy                           0.72      1407
   macro avg       0.68      0.73      0.68      1407
weighted avg       0.78      0.72      0.74      1407

In [39]:
model_rf_smoteenn = RandomForestClassifier(n_estimators=500)
model_rf_smoteenn.fit(X_train_resampled, y_train_resampled)

y_pred_rf_smoteenn = model_rf_smoteenn.predict(X_test)

In [40]:
print(classification_report(y_test, y_pred_rf_smoteenn))

              precision    recall  f1-score   support

           0       0.92      0.71      0.80      1049
           1       0.49      0.82      0.62       358

    accuracy                           0.74      1407
   macro avg       0.71      0.77      0.71      1407
weighted avg       0.81      0.74      0.75      1407

## XGBoost without SMOTEENN

In [41]:
from xgboost import XGBClassifier

# Initialize and train the XGBoost model
model_xgb = XGBClassifier(random_state=42)  # random_state for reproducibility
model_xgb.fit(X_train, y_train)

# Make predictions on the test set
y_pred_xgb = model_xgb.predict(X_test)

In [42]:
print(classification_report(y_test, y_pred_xgb))

              precision    recall  f1-score   support

           0       0.84      0.89      0.87      1049
           1       0.62      0.52      0.56       358

    accuracy                           0.80      1407
   macro avg       0.73      0.70      0.71      1407
weighted avg       0.79      0.80      0.79      1407

## XGBoost with SMOTEENN

In [43]:
from xgboost import XGBClassifier

# Initialize and train the XGBoost model
model_xgb_smoteenn = XGBClassifier(random_state=42)  # random_state for reproducibility
model_xgb_smoteenn.fit(X_train_resampled, y_train_resampled)

# Make predictions on the test set
y_pred_xgb_smoteenn = model_xgb_smoteenn.predict(X_test)

In [44]:
print(classification_report(y_test, y_pred_xgb_smoteenn))

              precision    recall  f1-score   support

           0       0.91      0.71      0.80      1049
           1       0.49      0.80      0.60       358

    accuracy                           0.73      1407
   macro avg       0.70      0.75      0.70      1407
weighted avg       0.80      0.73      0.75      1407

## XGBoost with SMOTE

In [45]:
from imblearn.over_sampling import SMOTE
from xgboost import XGBClassifier
from collections import Counter

# Check class distribution before SMOTE
print("Before SMOTE:", Counter(y_train))

# Apply SMOTE to the training data only
smote = SMOTE(random_state=42)
X_train_smote, y_train_smote = smote.fit_resample(X_train, y_train)

# Check class distribution after SMOTE
print("After SMOTE:", Counter(y_train_smote))

# Initialize and train the XGBoost model on resampled data
model_xgb_smote = XGBClassifier(random_state=42)
model_xgb_smote.fit(X_train_smote, y_train_smote)

# Make predictions on the original test set (unchanged)
y_pred_xgb_smote = model_xgb_smote.predict(X_test)

Before SMOTE: Counter({0: 4114, 1: 1511})
After SMOTE: Counter({0: 4114, 1: 4114})

In [46]:
print(classification_report(y_test, y_pred_xgb_smote))

              precision    recall  f1-score   support

           0       0.86      0.85      0.85      1049
           1       0.57      0.58      0.58       358

    accuracy                           0.78      1407
   macro avg       0.72      0.72      0.72      1407
weighted avg       0.78      0.78      0.78      1407

In [47]:
from imblearn.over_sampling import ADASYN
from xgboost import XGBClassifier
from collections import Counter

# Check original distribution
print("Before ADASYN:", Counter(y_train))

# Apply ADASYN to training data only
adasyn = ADASYN(random_state=42)
X_train_adasyn, y_train_adasyn = adasyn.fit_resample(X_train, y_train)

# Check new distribution
print("After ADASYN:", Counter(y_train_adasyn))

# Train XGBoost on ADASYN-resampled data
model_xgb_adasyn = XGBClassifier(random_state=42)
model_xgb_adasyn.fit(X_train_adasyn, y_train_adasyn)

# Predict on the original test set
y_pred_xgb_adasyn = model_xgb_adasyn.predict(X_test)

# Evaluate
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print("Accuracy:", accuracy_score(y_test, y_pred_xgb_adasyn))
print("\nClassification Report:\n", classification_report(y_test, y_pred_xgb_adasyn))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred_xgb_adasyn))

Before ADASYN: Counter({0: 4114, 1: 1511})
After ADASYN: Counter({1: 4127, 0: 4114})
Accuracy: 0.7846481876332623

Classification Report:
               precision    recall  f1-score   support

           0       0.85      0.86      0.86      1049
           1       0.58      0.57      0.57       358

    accuracy                           0.78      1407
   macro avg       0.72      0.71      0.71      1407
weighted avg       0.78      0.78      0.78      1407


Confusion Matrix:
 [[900 149]
 [154 204]]

In [49]:
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Calculate scale_pos_weight (ratio of negative to positive class)
scale_pos_weight = (y_train == 0).sum() / (y_train == 1).sum()
print(f"scale_pos_weight: {scale_pos_weight:.2f}")

# Train XGBoost with scale_pos_weight
model_xgb_weighted = XGBClassifier(
    scale_pos_weight=scale_pos_weight,
    random_state=42,
    eval_metric='logloss'  # avoids warnings
)

model_xgb_weighted.fit(X_train, y_train)
y_pred_weighted = model_xgb_weighted.predict(X_test)

# Evaluate
print("Accuracy:", accuracy_score(y_test, y_pred_weighted))
print("\nClassification Report:\n", classification_report(y_test, y_pred_weighted))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred_weighted))

scale_pos_weight: 2.72
Accuracy: 0.7761194029850746

Classification Report:
               precision    recall  f1-score   support

           0       0.90      0.79      0.84      1049
           1       0.54      0.73      0.62       358

    accuracy                           0.78      1407
   macro avg       0.72      0.76      0.73      1407
weighted avg       0.81      0.78      0.79      1407


Confusion Matrix:
 [[831 218]
 [ 97 261]]

In [50]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import numpy as np

# Calculate the weight for the positive (minority) class
# Common approach: weight_positive = negative_count / positive_count
negative_count = (y_train == 0).sum()
positive_count = (y_train == 1).sum()
weight_positive = negative_count / positive_count if positive_count > 0 else 1
print(f"Negative class count: {negative_count}")
print(f"Positive class count: {positive_count}")
print(f"Weight for positive class: {weight_positive:.2f}")

# Create sample weights: higher weight for minority class
sample_weight = np.where(y_train == 1, weight_positive, 1.0)

# Train AdaBoost with sample weights
model_ada_weighted = AdaBoostClassifier(
    n_estimators=50,  # default, you can tune
    random_state=42
)

model_ada_weighted.fit(X_train, y_train, sample_weight=sample_weight)

# Predict and evaluate
y_pred_ada_weighted = model_ada_weighted.predict(X_test)

print("AdaBoost with sample weighting - Accuracy:", accuracy_score(y_test, y_pred_ada_weighted))
print("\nClassification Report:\n", classification_report(y_test, y_pred_ada_weighted))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred_ada_weighted))

Negative class count: 4114
Positive class count: 1511
Weight for positive class: 2.72
AdaBoost with sample weighting - Accuracy: 0.738450604122246

Classification Report:
               precision    recall  f1-score   support

           0       0.92      0.71      0.80      1049
           1       0.49      0.81      0.61       358

    accuracy                           0.74      1407
   macro avg       0.70      0.76      0.71      1407
weighted avg       0.81      0.74      0.75      1407


Confusion Matrix:
 [[748 301]
 [ 67 291]]

## **Hyper Parameter Optimization**

In [51]:
from sklearn.model_selection import RandomizedSearchCV
from xgboost import XGBClassifier

param_grid = {
    'max_depth': [3, 4, 5, 6, 7],
    'learning_rate': [0.01, 0.05, 0.1, 0.2],
    'n_estimators': [100, 200, 300, 400],
    'subsample': [0.7, 0.8, 0.9, 1.0],
    'colsample_bytree': [0.7, 0.8, 0.9, 1.0],
    'min_child_weight': [1, 3, 5],
    'gamma': [0, 0.1, 0.2],
    'scale_pos_weight': [1, scale_pos_weight]  # try both balanced and weighted
}

xgb = XGBClassifier(random_state=42, eval_metric='logloss')

# Use 'f1' or 'recall' scoring since churn is imbalanced
search = RandomizedSearchCV(
    xgb,
    param_grid,
    n_iter=50,
    cv=5,
    scoring='f1',  # or 'recall' if catching churn is priority
    random_state=42,
    n_jobs=-1
)

search.fit(X_train, y_train)

print("Best parameters:", search.best_params_)
print("Best CV F1 score:", search.best_score_)

# Use best model
best_model = search.best_estimator_
y_pred_best = best_model.predict(X_test)
print("\nTest Classification Report:\n", classification_report(y_test, y_pred_best))

Best parameters: {'subsample': 0.7, 'scale_pos_weight': np.float64(2.7227001985440107), 'n_estimators': 400, 'min_child_weight': 3, 'max_depth': 7, 'learning_rate': 0.01, 'gamma': 0, 'colsample_bytree': 0.9}
Best CV F1 score: 0.6348154160351993

Test Classification Report:
               precision    recall  f1-score   support

           0       0.91      0.76      0.83      1049
           1       0.53      0.78      0.63       358

    accuracy                           0.76      1407
   macro avg       0.72      0.77      0.73      1407
weighted avg       0.81      0.76      0.78      1407

In [52]:
# Save this model

import joblib

# Save the best model to a .pkl file
joblib.dump(best_model, 'best_xgboost_churn_model.pkl')

print("Best model successfully saved as 'best_xgboost_churn_model.pkl'")

Best model successfully saved as 'best_xgboost_churn_model.pkl'

## Trying out few more techniques

In [53]:
from sklearn.ensemble import RandomForestClassifier

model_rf = RandomForestClassifier(
    class_weight='balanced',
    random_state=42,
    n_estimators=300,
    max_depth=6
)
model_rf.fit(X_train, y_train)
y_pred_rf = model_rf.predict(X_test)
print(classification_report(y_test, y_pred_rf))

              precision    recall  f1-score   support

           0       0.92      0.71      0.80      1049
           1       0.50      0.83      0.62       358

    accuracy                           0.74      1407
   macro avg       0.71      0.77      0.71      1407
weighted avg       0.82      0.74      0.76      1407

In [56]:
!pip install catboost

from catboost import CatBoostClassifier

model_cat = CatBoostClassifier(
    auto_class_weights='Balanced',  # or 'SqrtBalanced'
    verbose=0,
    random_state=42
)
model_cat.fit(X_train, y_train)
y_pred_cat = model_cat.predict(X_test)
print(classification_report(y_test, y_pred_cat))

Requirement already satisfied: catboost in /usr/local/lib/python3.12/dist-packages (1.2.10)
Requirement already satisfied: graphviz in /usr/local/lib/python3.12/dist-packages (from catboost) (0.21)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from catboost) (3.10.0)
Requirement already satisfied: numpy<3.0,>=1.16.0 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.0.2)
Requirement already satisfied: pandas<4.0,>=0.24 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.2.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from catboost) (1.16.3)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (from catboost) (5.24.1)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2026.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (26.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (3.3.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly->catboost) (9.1.4)
              precision    recall  f1-score   support

           0       0.91      0.76      0.83      1049
           1       0.53      0.78      0.63       358

    accuracy                           0.76      1407
   macro avg       0.72      0.77      0.73      1407
weighted avg       0.81      0.76      0.78      1407

In [57]:
from lightgbm import LGBMClassifier

model_lgb = LGBMClassifier(
    scale_pos_weight=scale_pos_weight,
    random_state=42
)
model_lgb.fit(X_train, y_train)
y_pred_lgb = model_lgb.predict(X_test)
print(classification_report(y_test, y_pred_lgb))

[LightGBM] [Info] Number of positive: 1511, number of negative: 4114
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.012649 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 606
[LightGBM] [Info] Number of data points in the train set: 5625, number of used features: 34
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.268622 -> initscore=-1.001624
[LightGBM] [Info] Start training from score -1.001624
              precision    recall  f1-score   support

           0       0.90      0.77      0.83      1049
           1       0.53      0.76      0.62       358

    accuracy                           0.76      1407
   macro avg       0.71      0.76      0.72      1407
weighted avg       0.81      0.76      0.78      1407

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

## **Optuna fine tuning**

In [59]:
!pip install optuna

Collecting optuna
  Downloading optuna-4.9.0-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (1.18.4)
Collecting colorlog (from optuna)
  Downloading colorlog-6.10.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (26.2)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.50)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna) (4.67.3)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna) (6.0.3)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (1.3.12)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (4.15.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.5.1)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from Mako->alembic>=1.5.0->optuna) (3.0.3)
Downloading optuna-4.9.0-py3-none-any.whl (425 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 425.6/425.6 kB 8.0 MB/s eta 0:00:00
Downloading colorlog-6.10.1-py3-none-any.whl (11 kB)
Installing collected packages: colorlog, optuna
Successfully installed colorlog-6.10.1 optuna-4.9.0

In [60]:
import optuna
from sklearn.model_selection import cross_val_score
from xgboost import XGBClassifier
from sklearn.metrics import f1_score, make_scorer

def objective(trial):
    params = {
        'max_depth': trial.suggest_int('max_depth', 3, 10),
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.3, log=True),
        'n_estimators': trial.suggest_int('n_estimators', 100, 1000),
        'subsample': trial.suggest_float('subsample', 0.6, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.6, 1.0),
        'min_child_weight': trial.suggest_int('min_child_weight', 1, 10),
        'gamma': trial.suggest_float('gamma', 0, 0.5),
        'reg_alpha': trial.suggest_float('reg_alpha', 0, 1),  # L1 regularization
        'reg_lambda': trial.suggest_float('reg_lambda', 0, 2), # L2 regularization
        'scale_pos_weight': trial.suggest_categorical('scale_pos_weight', [1, scale_pos_weight]),
        'random_state': 42,
        'eval_metric': 'logloss'
    }

    model = XGBClassifier(**params)

    # Use F1 for minority class as scorer
    f1_scorer = make_scorer(f1_score, average='binary', pos_label=1)
    score = cross_val_score(model, X_train, y_train, cv=5, scoring=f1_scorer, n_jobs=-1).mean()

    return score

study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=100)  # Increase trials for better results

print("Best parameters:", study.best_params)
print("Best CV F1 score:", study.best_value)

# Train final model with best params
best_model_optuna = XGBClassifier(**study.best_params)
best_model_optuna.fit(X_train, y_train)
y_pred_optuna = best_model_optuna.predict(X_test)
print(classification_report(y_test, y_pred_optuna))

[I 2026-06-15 19:17:19,764] A new study created in memory with name: no-name-b8dac767-4fd1-466a-980d-e63392067449
[I 2026-06-15 19:17:27,267] Trial 0 finished with value: 0.5164657046679455 and parameters: {'max_depth': 10, 'learning_rate': 0.014816307676041, 'n_estimators': 115, 'subsample': 0.8622091136143777, 'colsample_bytree': 0.6744299466462941, 'min_child_weight': 3, 'gamma': 0.20873727224771643, 'reg_alpha': 0.6561553819187985, 'reg_lambda': 1.224748103968262, 'scale_pos_weight': 1}. Best is trial 0 with value: 0.5164657046679455.
[I 2026-06-15 19:17:38,090] Trial 1 finished with value: 0.573184794167665 and parameters: {'max_depth': 8, 'learning_rate': 0.011672677668194735, 'n_estimators': 546, 'subsample': 0.6239856131164699, 'colsample_bytree': 0.6791588012129184, 'min_child_weight': 1, 'gamma': 0.2432200573526751, 'reg_alpha': 0.4657628294998003, 'reg_lambda': 0.7680437455605822, 'scale_pos_weight': 1}. Best is trial 1 with value: 0.573184794167665.
[I 2026-06-15 19:17:46,250] Trial 2 finished with value: 0.5709020699191665 and parameters: {'max_depth': 8, 'learning_rate': 0.01185718757407515, 'n_estimators': 812, 'subsample': 0.657050616983693, 'colsample_bytree': 0.6321048178941208, 'min_child_weight': 6, 'gamma': 0.07195433885465485, 'reg_alpha': 0.9076117075932996, 'reg_lambda': 0.010418377399567413, 'scale_pos_weight': 1}. Best is trial 1 with value: 0.573184794167665.
[I 2026-06-15 19:17:47,382] Trial 3 finished with value: 0.6153673401974513 and parameters: {'max_depth': 3, 'learning_rate': 0.26835475238736856, 'n_estimators': 194, 'subsample': 0.6999848564753284, 'colsample_bytree': 0.6082571172692893, 'min_child_weight': 5, 'gamma': 0.09628168537035553, 'reg_alpha': 0.1441560381358915, 'reg_lambda': 1.2307418730317086, 'scale_pos_weight': np.float64(2.7227001985440107)}. Best is trial 3 with value: 0.6153673401974513.
[I 2026-06-15 19:17:51,630] Trial 4 finished with value: 0.5573956294756768 and parameters: {'max_depth': 7, 'learning_rate': 0.19077356169564136, 'n_estimators': 855, 'subsample': 0.6656875455611353, 'colsample_bytree': 0.66920080205618, 'min_child_weight': 7, 'gamma': 0.06322927991500243, 'reg_alpha': 0.09450081262882604, 'reg_lambda': 1.3984678572786777, 'scale_pos_weight': np.float64(2.7227001985440107)}. Best is trial 3 with value: 0.6153673401974513.
[I 2026-06-15 19:17:52,463] Trial 5 finished with value: 0.5753699269537986 and parameters: {'max_depth': 3, 'learning_rate': 0.11075177683610223, 'n_estimators': 241, 'subsample': 0.7823674592672077, 'colsample_bytree': 0.6693574921192471, 'min_child_weight': 9, 'gamma': 0.3662275051105018, 'reg_alpha': 0.12787309731428842, 'reg_lambda': 1.04838308397465, 'scale_pos_weight': 1}. Best is trial 3 with value: 0.6153673401974513.
[I 2026-06-15 19:17:56,077] Trial 6 finished with value: 0.5506075438763534 and parameters: {'max_depth': 6, 'learning_rate': 0.21903393219957795, 'n_estimators': 815, 'subsample': 0.7953981319668042, 'colsample_bytree': 0.6329950709758105, 'min_child_weight': 1, 'gamma': 0.07453767535132805, 'reg_alpha': 0.5943113826396937, 'reg_lambda': 0.05252317516554461, 'scale_pos_weight': np.float64(2.7227001985440107)}. Best is trial 3 with value: 0.6153673401974513.
[I 2026-06-15 19:17:59,052] Trial 7 finished with value: 0.5601875056848425 and parameters: {'max_depth': 10, 'learning_rate': 0.18231952711992488, 'n_estimators': 467, 'subsample': 0.7737074371227234, 'colsample_bytree': 0.6495160173143256, 'min_child_weight': 2, 'gamma': 0.18895989711288275, 'reg_alpha': 0.6825727445346175, 'reg_lambda': 0.5690952624903265, 'scale_pos_weight': np.float64(2.7227001985440107)}. Best is trial 3 with value: 0.6153673401974513.
[I 2026-06-15 19:18:03,591] Trial 8 finished with value: 0.556930561868776 and parameters: {'max_depth': 10, 'learning_rate': 0.20343498964005757, 'n_estimators': 634, 'subsample': 0.8626316677818948, 'colsample_bytree': 0.7622371576724974, 'min_child_weight': 6, 'gamma': 0.09927122835616359, 'reg_alpha': 0.29157869084736165, 'reg_lambda': 1.8738872529240802, 'scale_pos_weight': np.float64(2.7227001985440107)}. Best is trial 3 with value: 0.6153673401974513.
[I 2026-06-15 19:18:07,683] Trial 9 finished with value: 0.5811344163763168 and parameters: {'max_depth': 6, 'learning_rate': 0.07893514795124375, 'n_estimators': 988, 'subsample': 0.8200674119626888, 'colsample_bytree': 0.929276121349, 'min_child_weight': 4, 'gamma': 0.49571478197563845, 'reg_alpha': 0.2876994079567158, 'reg_lambda': 0.9118468147754506, 'scale_pos_weight': np.float64(2.7227001985440107)}. Best is trial 3 with value: 0.6153673401974513.
[I 2026-06-15 19:18:08,834] Trial 10 finished with value: 0.6287444500577701 and parameters: {'max_depth': 3, 'learning_rate': 0.03178515552443869, 'n_estimators': 342, 'subsample': 0.9886516355787659, 'colsample_bytree': 0.9940568265154439, 'min_child_weight': 10, 'gamma': 0.36506578763233605, 'reg_alpha': 0.9893467979625845, 'reg_lambda': 1.9686451621506098, 'scale_pos_weight': np.float64(2.7227001985440107)}. Best is trial 10 with value: 0.6287444500577701.
[I 2026-06-15 19:18:09,948] Trial 11 finished with value: 0.6319882960248858 and parameters: {'max_depth': 3, 'learning_rate': 0.03494057587184075, 'n_estimators': 325, 'subsample': 0.9981745741277832, 'colsample_bytree': 0.9981457358342037, 'min_child_weight': 10, 'gamma': 0.35098533717949054, 'reg_alpha': 0.9922957757459802, 'reg_lambda': 1.9957479237903684, 'scale_pos_weight': np.float64(2.7227001985440107)}. Best is trial 11 with value: 0.6319882960248858.
[I 2026-06-15 19:18:11,361] Trial 12 finished with value: 0.629599706882178 and parameters: {'max_depth': 4, 'learning_rate': 0.03217748106641119, 'n_estimators': 372, 'subsample': 0.9932081783081163, 'colsample_bytree': 0.9961351181831527, 'min_child_weight': 10, 'gamma': 0.37030197142264404, 'reg_alpha': 0.9705828296543473, 'reg_lambda': 1.9816437628263273, 'scale_pos_weight': np.float64(2.7227001985440107)}. Best is trial 11 with value: 0.6319882960248858.
[I 2026-06-15 19:18:13,822] Trial 13 finished with value: 0.6261807986131007 and parameters: {'max_depth': 5, 'learning_rate': 0.033275658359918255, 'n_estimators': 366, 'subsample': 0.9925956577752441, 'colsample_bytree': 0.9177323240507819, 'min_child_weight': 9, 'gamma': 0.36619954448873104, 'reg_alpha': 0.8698904278119513, 'reg_lambda': 1.6464225885803063, 'scale_pos_weight': np.float64(2.7227001985440107)}. Best is trial 11 with value: 0.6319882960248858.
[I 2026-06-15 19:18:15,742] Trial 14 finished with value: 0.6302594220886387 and parameters: {'max_depth': 4, 'learning_rate': 0.03478633035021742, 'n_estimators': 382, 'subsample': 0.9350213375979909, 'colsample_bytree': 0.9999434731700962, 'min_child_weight': 10, 'gamma': 0.4745490336955517, 'reg_alpha': 0.7867609515810374, 'reg_lambda': 1.6334964091626585, 'scale_pos_weight': np.float64(2.7227001985440107)}. Best is trial 11 with value: 0.6319882960248858.
[I 2026-06-15 19:18:17,658] Trial 15 finished with value: 0.616416582567077 and parameters: {'max_depth': 4, 'learning_rate': 0.05785903600895353, 'n_estimators': 613, 'subsample': 0.9365337302594307, 'colsample_bytree': 0.909089224458755, 'min_child_weight': 8, 'gamma': 0.483488283885968, 'reg_alpha': 0.8128202071853475, 'reg_lambda': 1.611349852550126, 'scale_pos_weight': np.float64(2.7227001985440107)}. Best is trial 11 with value: 0.6319882960248858.
[I 2026-06-15 19:18:18,837] Trial 16 finished with value: 0.6294394831284744 and parameters: {'max_depth': 4, 'learning_rate': 0.02093434168355548, 'n_estimators': 273, 'subsample': 0.9319570445982178, 'colsample_bytree': 0.8545550524693644, 'min_child_weight': 8, 'gamma': 0.44016919825984246, 'reg_alpha': 0.7606267567775081, 'reg_lambda': 1.704850734862539, 'scale_pos_weight': np.float64(2.7227001985440107)}. Best is trial 11 with value: 0.6319882960248858.
[I 2026-06-15 19:18:20,876] Trial 17 finished with value: 0.6205546527493391 and parameters: {'max_depth': 5, 'learning_rate': 0.04949437416078156, 'n_estimators': 494, 'subsample': 0.9325528188736539, 'colsample_bytree': 0.9637295525849068, 'min_child_weight': 10, 'gamma': 0.30722739468277793, 'reg_alpha': 0.7891302312342809, 'reg_lambda': 1.4749086816515644, 'scale_pos_weight': np.float64(2.7227001985440107)}. Best is trial 11 with value: 0.6319882960248858.
[I 2026-06-15 19:18:22,928] Trial 18 finished with value: 0.5865335074574981 and parameters: {'max_depth': 5, 'learning_rate': 0.020950017448347617, 'n_estimators': 438, 'subsample': 0.9038797212351535, 'colsample_bytree': 0.8268713460897293, 'min_child_weight': 8, 'gamma': 0.42829578769430887, 'reg_alpha': 0.5530557802627954, 'reg_lambda': 1.7706342733175129, 'scale_pos_weight': 1}. Best is trial 11 with value: 0.6319882960248858.
[I 2026-06-15 19:18:23,606] Trial 19 finished with value: 0.6332166191029392 and parameters: {'max_depth': 4, 'learning_rate': 0.055689411951140126, 'n_estimators': 130, 'subsample': 0.8900485036810569, 'colsample_bytree': 0.8688872965419784, 'min_child_weight': 9, 'gamma': 0.2837874594216112, 'reg_alpha': 0.43208520625400065, 'reg_lambda': 1.416413019738362, 'scale_pos_weight': np.float64(2.7227001985440107)}. Best is trial 19 with value: 0.6332166191029392.
[I 2026-06-15 19:18:24,201] Trial 20 finished with value: 0.6263868483800111 and parameters: {'max_depth': 3, 'learning_rate': 0.10712078882354333, 'n_estimators': 135, 'subsample': 0.7346521721436783, 'colsample_bytree': 0.8333965293068625, 'min_child_weight': 9, 'gamma': 0.2914283907549844, 'reg_alpha': 0.3706242029731758, 'reg_lambda': 0.48178810193455357, 'scale_pos_weight': np.float64(2.7227001985440107)}. Best is trial 19 with value: 0.6332166191029392.
[I 2026-06-15 19:18:25,438] Trial 21 finished with value: 0.6316858236009973 and parameters: {'max_depth': 4, 'learning_rate': 0.04666952082827981, 'n_estimators': 262, 'subsample': 0.8596726858333008, 'colsample_bytree': 0.877437535879332, 'min_child_weight': 10, 'gamma': 0.29183650796712746, 'reg_alpha': 0.9086391839902953, 'reg_lambda': 1.500976697321983, 'scale_pos_weight': np.float64(2.7227001985440107)}. Best is trial 19 with value: 0.6332166191029392.
[I 2026-06-15 19:18:27,337] Trial 22 finished with value: 0.6307874172322527 and parameters: {'max_depth': 4, 'learning_rate': 0.05735955038247526, 'n_estimators': 277, 'subsample': 0.8635649423517422, 'colsample_bytree': 0.8746412518752681, 'min_child_weight': 9, 'gamma': 0.29631164153484374, 'reg_alpha': 0.9079833254749452, 'reg_lambda': 1.3984466001285685, 'scale_pos_weight': np.float64(2.7227001985440107)}. Best is trial 19 with value: 0.6332166191029392.
[I 2026-06-15 19:18:29,337] Trial 23 finished with value: 0.6327688673926325 and parameters: {'max_depth': 5, 'learning_rate': 0.04716201817868601, 'n_estimators': 186, 'subsample': 0.8953971323806155, 'colsample_bytree': 0.7811615011428678, 'min_child_weight': 7, 'gamma': 0.1540879491478391, 'reg_alpha': 0.40748020608372176, 'reg_lambda': 1.2179592202798544, 'scale_pos_weight': np.float64(2.7227001985440107)}. Best is trial 19 with value: 0.6332166191029392.
[I 2026-06-15 19:18:31,210] Trial 24 finished with value: 0.6242779832735353 and parameters: {'max_depth': 6, 'learning_rate': 0.08185241996838949, 'n_estimators': 175, 'subsample': 0.9123795590475391, 'colsample_bytree': 0.7683656576498534, 'min_child_weight': 7, 'gamma': 0.17327506826192418, 'reg_alpha': 0.44422108975663566, 'reg_lambda': 1.189545667775131, 'scale_pos_weight': np.float64(2.7227001985440107)}. Best is trial 19 with value: 0.6332166191029392.
[I 2026-06-15 19:18:32,449] Trial 25 finished with value: 0.6270486326518026 and parameters: {'max_depth': 5, 'learning_rate': 0.02213843810308346, 'n_estimators': 106, 'subsample': 0.9599213911475388, 'colsample_bytree': 0.7741771250153876, 'min_child_weight': 7, 'gamma': 0.14133267607733932, 'reg_alpha': 0.24538359792629028, 'reg_lambda': 1.0322513989026283, 'scale_pos_weight': np.float64(2.7227001985440107)}. Best is trial 19 with value: 0.6332166191029392.
[I 2026-06-15 19:18:33,802] Trial 26 finished with value: 0.586962180731111 and parameters: {'max_depth': 3, 'learning_rate': 0.07447107420998729, 'n_estimators': 197, 'subsample': 0.8986964626051832, 'colsample_bytree': 0.8074308103218789, 'min_child_weight': 8, 'gamma': 0.23617583529421002, 'reg_alpha': 0.48935124194685214, 'reg_lambda': 0.6843249457381572, 'scale_pos_weight': 1}. Best is trial 19 with value: 0.6332166191029392.
[I 2026-06-15 19:18:36,364] Trial 27 finished with value: 0.6280834239220275 and parameters: {'max_depth': 5, 'learning_rate': 0.041948574843624756, 'n_estimators': 309, 'subsample': 0.8298258593096406, 'colsample_bytree': 0.7302495986313969, 'min_child_weight': 6, 'gamma': 0.13700359932184614, 'reg_alpha': 0.37803137147439975, 'reg_lambda': 0.2863393621299162, 'scale_pos_weight': np.float64(2.7227001985440107)}. Best is trial 19 with value: 0.6332166191029392.
[I 2026-06-15 19:18:39,239] Trial 28 finished with value: 0.6319399786929858 and parameters: {'max_depth': 6, 'learning_rate': 0.025690444890868653, 'n_estimators': 185, 'subsample': 0.9615513555108163, 'colsample_bytree': 0.7238543524847585, 'min_child_weight': 9, 'gamma': 0.3342931104550998, 'reg_alpha': 0.02056056613946078, 'reg_lambda': 1.3271832341689878, 'scale_pos_weight': np.float64(2.7227001985440107)}. Best is trial 19 with value: 0.6332166191029392.
[I 2026-06-15 19:18:41,885] Trial 29 finished with value: 0.5625495674936215 and parameters: {'max_depth': 7, 'learning_rate': 0.10094245368741342, 'n_estimators': 115, 'subsample': 0.8834829272088233, 'colsample_bytree': 0.9532410352079049, 'min_child_weight': 4, 'gamma': 0.2413476347067574, 'reg_alpha': 0.6285840833592096, 'reg_lambda': 1.176536520425078, 'scale_pos_weight': 1}. Best is trial 19 with value: 0.6332166191029392.
[I 2026-06-15 19:18:43,459] Trial 30 finished with value: 0.6289378567667354 and parameters: {'max_depth': 3, 'learning_rate': 0.016858524985607984, 'n_estimators': 225, 'subsample': 0.9609543262243682, 'colsample_bytree': 0.7983675565090367, 'min_child_weight': 7, 'gamma': 0.0057375601322800784, 'reg_alpha': 0.699478079124548, 'reg_lambda': 1.8053534157849196, 'scale_pos_weight': np.float64(2.7227001985440107)}. Best is trial 19 with value: 0.6332166191029392.
[I 2026-06-15 19:18:45,059] Trial 31 finished with value: 0.6313818640682742 and parameters: {'max_depth': 6, 'learning_rate': 0.024265227928649456, 'n_estimators': 143, 'subsample': 0.963878486469894, 'colsample_bytree': 0.7247558993076889, 'min_child_weight': 9, 'gamma': 0.3350028974693196, 'reg_alpha': 0.1923408600188146, 'reg_lambda': 1.3286167039604506, 'scale_pos_weight': np.float64(2.7227001985440107)}. Best is trial 19 with value: 0.6332166191029392.
[I 2026-06-15 19:18:47,040] Trial 32 finished with value: 0.6295095004213502 and parameters: {'max_depth': 7, 'learning_rate': 0.02719671727391935, 'n_estimators': 171, 'subsample': 0.9643983276219275, 'colsample_bytree': 0.7136089331542387, 'min_child_weight': 8, 'gamma': 0.41311944960901703, 'reg_alpha': 0.01332643303382025, 'reg_lambda': 1.283414805299786, 'scale_pos_weight': np.float64(2.7227001985440107)}. Best is trial 19 with value: 0.6332166191029392.
[I 2026-06-15 19:18:50,696] Trial 33 finished with value: 0.633736720189965 and parameters: {'max_depth': 9, 'learning_rate': 0.014436424053947924, 'n_estimators': 320, 'subsample': 0.8847157756180808, 'colsample_bytree': 0.7031911495223306, 'min_child_weight': 9, 'gamma': 0.26190397123176323, 'reg_alpha': 0.013805855922748068, 'reg_lambda': 0.9066715636337507, 'scale_pos_weight': np.float64(2.7227001985440107)}. Best is trial 33 with value: 0.633736720189965.
[I 2026-06-15 19:18:54,262] Trial 34 finished with value: 0.5751617356676524 and parameters: {'max_depth': 9, 'learning_rate': 0.014240764537069303, 'n_estimators': 419, 'subsample': 0.8281658799944756, 'colsample_bytree': 0.7012512067217244, 'min_child_weight': 10, 'gamma': 0.25669581119648366, 'reg_alpha': 0.5254879349142407, 'reg_lambda': 0.8504494225698128, 'scale_pos_weight': 1}. Best is trial 33 with value: 0.633736720189965.
[I 2026-06-15 19:18:57,098] Trial 35 finished with value: 0.6206749983014337 and parameters: {'max_depth': 9, 'learning_rate': 0.016387955758115552, 'n_estimators': 313, 'subsample': 0.890463761465993, 'colsample_bytree': 0.792361613174082, 'min_child_weight': 5, 'gamma': 0.21589512838518823, 'reg_alpha': 0.3719611722514542, 'reg_lambda': 1.0365128341316636, 'scale_pos_weight': np.float64(2.7227001985440107)}. Best is trial 33 with value: 0.633736720189965.
[I 2026-06-15 19:18:59,458] Trial 36 finished with value: 0.6310142072567484 and parameters: {'max_depth': 8, 'learning_rate': 0.010052901178789864, 'n_estimators': 227, 'subsample': 0.8493844741185653, 'colsample_bytree': 0.7491279629640752, 'min_child_weight': 8, 'gamma': 0.2597478981593458, 'reg_alpha': 0.07613133416649155, 'reg_lambda': 0.7477963603080519, 'scale_pos_weight': np.float64(2.7227001985440107)}. Best is trial 33 with value: 0.633736720189965.
[I 2026-06-15 19:19:01,559] Trial 37 finished with value: 0.6149250027719836 and parameters: {'max_depth': 9, 'learning_rate': 0.03987411474429951, 'n_estimators': 314, 'subsample': 0.7504014014959158, 'colsample_bytree': 0.6849854165268592, 'min_child_weight': 9, 'gamma': 0.16162509151570692, 'reg_alpha': 0.1820316087520104, 'reg_lambda': 0.922261728543107, 'scale_pos_weight': np.float64(2.7227001985440107)}. Best is trial 33 with value: 0.633736720189965.
[I 2026-06-15 19:19:04,142] Trial 38 finished with value: 0.5515811407428293 and parameters: {'max_depth': 8, 'learning_rate': 0.06688166083942125, 'n_estimators': 523, 'subsample': 0.8814426293339583, 'colsample_bytree': 0.6081885250719816, 'min_child_weight': 7, 'gamma': 0.21059813489686935, 'reg_alpha': 0.44500565028970585, 'reg_lambda': 1.0971214015058364, 'scale_pos_weight': 1}. Best is trial 33 with value: 0.633736720189965.
[I 2026-06-15 19:19:06,639] Trial 39 finished with value: 0.6311064314125967 and parameters: {'max_depth': 3, 'learning_rate': 0.013257780431796554, 'n_estimators': 570, 'subsample': 0.788988014765337, 'colsample_bytree': 0.8852526210149887, 'min_child_weight': 6, 'gamma': 0.33108575170654264, 'reg_alpha': 0.7325897449198093, 'reg_lambda': 1.4970874964045005, 'scale_pos_weight': np.float64(2.7227001985440107)}. Best is trial 33 with value: 0.633736720189965.
[I 2026-06-15 19:19:11,368] Trial 40 finished with value: 0.575521949938717 and parameters: {'max_depth': 10, 'learning_rate': 0.14204486204195255, 'n_estimators': 683, 'subsample': 0.8474539720477485, 'colsample_bytree': 0.8405280242564057, 'min_child_weight': 5, 'gamma': 0.3965416333488545, 'reg_alpha': 0.5938955417248838, 'reg_lambda': 0.62910312458716, 'scale_pos_weight': np.float64(2.7227001985440107)}. Best is trial 33 with value: 0.633736720189965.
[I 2026-06-15 19:19:12,612] Trial 41 finished with value: 0.6326766380623965 and parameters: {'max_depth': 7, 'learning_rate': 0.026878883585472274, 'n_estimators': 187, 'subsample': 0.9156485737228446, 'colsample_bytree': 0.7367439366902401, 'min_child_weight': 9, 'gamma': 0.34408912189813856, 'reg_alpha': 0.03368723430403807, 'reg_lambda': 1.1194353011066012, 'scale_pos_weight': np.float64(2.7227001985440107)}. Best is trial 33 with value: 0.633736720189965.
[I 2026-06-15 19:19:13,942] Trial 42 finished with value: 0.6189206886851847 and parameters: {'max_depth': 7, 'learning_rate': 0.05259822141600176, 'n_estimators': 232, 'subsample': 0.9095079114901331, 'colsample_bytree': 0.6865375465540444, 'min_child_weight': 9, 'gamma': 0.27363007437573855, 'reg_alpha': 0.08459526905601396, 'reg_lambda': 0.9292526472249002, 'scale_pos_weight': np.float64(2.7227001985440107)}. Best is trial 33 with value: 0.633736720189965.

Best parameters: {'max_depth': 8, 'learning_rate': 0.011015452507158725, 'n_estimators': 204, 'subsample': 0.6165138071650915, 'colsample_bytree': 0.7004641281654851, 'min_child_weight': 2, 'gamma': 0.10093257820815771, 'reg_alpha': 0.06686676041216275, 'reg_lambda': 0.9904367559274321, 'scale_pos_weight': np.float64(2.7227001985440107)}
Best CV F1 score: 0.6362712991953223
              precision    recall  f1-score   support

           0       0.91      0.76      0.83      1049
           1       0.53      0.78      0.63       358

    accuracy                           0.77      1407
   macro avg       0.72      0.77      0.73      1407
weighted avg       0.81      0.77      0.78      1407

In [61]:
# Save this model

import joblib

# Save the best model to a .pkl file
joblib.dump(best_model_optuna, 'best_optuna_churn_model.pkl')

print("Best model successfully saved as 'best_optuna_churn_model.pkl'")

Best model successfully saved as 'best_optuna_churn_model.pkl'

In [62]:
# Save this model

import joblib

# Save the best model to a .pkl file
joblib.dump(model_ada_weighted, 'ada_boost_churn_model.pkl')

print("Best model successfully saved as 'ada_boost_churn_model.pkl'")

Best model successfully saved as 'ada_boost_churn_model.pkl'